In [1]:
#create a numpy array

In [2]:
import numpy as np


In [5]:
arr=np.array([[2,3,4],[7,8,9],[0,1,3],[5,2,1]])
arr

array([[2, 3, 4],
       [7, 8, 9],
       [0, 1, 3],
       [5, 2, 1]])

In [6]:
arr.shape #to check size of array

(4, 3)

In [7]:
arr.ndim #to check the dimension of numpy array

2

In [8]:
#uses of type() and dtype() function

In [9]:
type(arr)

numpy.ndarray

In [10]:
arr.dtype

dtype('int32')

In [11]:
#python doestnot support dtype array 

In [12]:
pythonlist=[1,2,3,7]
pythonlist

[1, 2, 3, 7]

In [13]:
type(pythonlist)

list

In [14]:
pythonlist.dtype

AttributeError: 'list' object has no attribute 'dtype'

In [15]:
#Basic numpy arrays

In [16]:
#using array
arr=np.array([[2,3,1],[1,9,3],[8,2,1]])
arr

array([[2, 3, 1],
       [1, 9, 3],
       [8, 2, 1]])

In [17]:
#using arange
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
#using zeros
arr=np.zeros(10)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [19]:
#using ones
arr=np.ones(7)
arr

array([1., 1., 1., 1., 1., 1., 1.])

In [24]:
arr=np.linspace(start=2,stop=10,num=5)
arr

array([ 2.,  4.,  6.,  8., 10.])