In [2]:
import numpy as np

In [3]:
arr=np.array([10,20,30,70])
arr

array([10, 20, 30, 70])

In [4]:
arr[0] # here number representing the index

10

In [5]:
arr[1]

20

In [6]:
#python nested list

In [7]:
pythonlist=[[2,3,4],[1,0,9]]

In [8]:
pythonlist[0][1]

3

In [10]:
num_array=np.array(pythonlist)
num_array

array([[2, 3, 4],
       [1, 0, 9]])

In [11]:
num_array[0]

array([2, 3, 4])

In [12]:
num_array[0,1]

3

In [13]:
#positive index interval

In [ ]:
num