In [10]:
#adding an element

In [11]:
import numpy as np

In [14]:
arr=np.array([1,2,3,8,9])
arr


array([1, 2, 3, 8, 9])

In [15]:
np.append(arr,10) #adding element in the array

array([ 1,  2,  3,  8,  9, 10])

In [16]:
#python list support append method directly but numpy array doesn;t support append method directly

In [17]:
arr.append(10)#array doesn;t support append method directly

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [18]:
p=[1,2,3,4]
p.append(10)
p

[1, 2, 3, 4, 10]

In [21]:
#removing an element
np.delete(arr,0)

array([2, 3, 8, 9])

In [22]:
#sorting an array

In [23]:
np.sort(arr)

array([1, 2, 3, 8, 9])

In [25]:
arr=np.arange(24)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [27]:
#reshaping in shape(3,8)
np.reshape(arr,(3,8))

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [28]:
np.reshape(arr,(6,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [29]:
type(arr)

numpy.ndarray

In [30]:
#Using reshape() method on a Python list will throw an ‘AttributeError’

In [31]:
p=[2,3,0,9,8,7]
p.reshape(2,3)

AttributeError: 'list' object has no attribute 'reshape'